### ISSUE TITLE
java.lang.ClassNotFoundException: gnu.trove.map.TIntObjectMap

### ISSUE THREAD

**Issue by joery1337** [Calyps0/FPAgar#1]
Hey,

I tried running the server.

`Exception in thread "main" java.lang.NoClassDefFoundError: gnu/trove/map/TIntObjectMap
        at ru.calypso.ogar.server.OgarServer.run(OgarServer.java:144)
        at ru.calypso.ogar.server.OgarServer.main(OgarServer.java:76)
Caused by: java.lang.ClassNotFoundException: gnu.trove.map.TIntObjectMap
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 2 more`

**Comment by CalypsoToolz** [comment]
Check whether there is a trove-3.0.0a5.jar library in the libs folder.

**Comment by joery1337** [comment]
@Calyps0 It is, I have also tried the latest version, no change.

**Comment by CalypsoToolz** [comment]
How to the project was compiled ? How to be runned? (Translated text, sorry)

**Comment by joery1337** [comment]
@Calyps0 Got it working, I've no idea what the problems was.

**Comment by CalypsoToolz** [comment]
Thank you for using my build . I'll wait for bug reports - I'll Fix as much as possible.
